import type { FavoriteJobProps } from "../components/atoms/list";

export const mockFavoriteJobs: FavoriteJobProps[] = [
  {
    id: 1,
    companyName: "삼성전자",
    title: "소프트웨어 엔지니어 (Android 플랫폼)",
    location: "경기도 수원시",
    createTime: "2024-08-01",
    expLevel: "신입",
  },
  {
    id: 2,
    companyName: "삼성SDS",
    title: "클라우드 플랫폼 개발자",
    location: "서울시 강남구",
    createTime: "2024-07-28",
    expLevel: "경력 3년 이상",
  },
  {
    id: 3,
    companyName: "삼성디스플레이",
    title: "AI/ML 엔지니어 (Computer Vision)",
    location: "경기도 용인시",
    createTime: "2024-07-25",
    expLevel: "경력 2년 이상",
  },
  {
    id: 4,
    companyName: "삼성바이오로직스",
    title: "데이터 분석가 (바이오 인포매틱스)",
    location: "인천시 연수구",
    createTime: "2024-07-30",
    expLevel: "신입/경력",
  },
  {
    id: 5,
    companyName: "삼성물산",
    title: "백엔드 개발자 (Java/Spring)",
    location: "서울시 중구",
    createTime: "2024-08-03",
    expLevel: "경력 1년 이상",
  },
  {
    id: 6,
    companyName: "삼성증권",
    title: "핀테크 개발자 (React/Node.js)",
    location: "서울시 영등포구",
    createTime: "2024-07-22",
    expLevel: "경력 2년 이상",
  },
  {
    id: 7,
    companyName: "삼성화재",
    title: "보험 시스템 개발자",
    location: "서울시 중구",
    createTime: "2024-07-20",
    expLevel: "신입",
  },
  {
    id: 8,
    companyName: "삼성웰스토리",
    title: "모바일 앱 개발자 (Flutter)",
    location: "경기도 성남시",
    createTime: "2024-08-02",
    expLevel: "경력 1년 이상",
  },
  {
    id: 9,
    companyName: "삼성생명",
    title: "데브옵스 엔지니어",
    location: "서울시 중구",
    createTime: "2024-07-26",
    expLevel: "경력 3년 이상",
  },
  {
    id: 10,
    companyName: "삼성중공업",
    title: "산업용 IoT 개발자",
    location: "경상남도 거제시",
    createTime: "2024-07-29",
    expLevel: "경력 2년 이상",
  },
];
