import type { ApplicationItemProps } from "../components/atoms/listItem";

export const mockApplications: ApplicationItemProps[] = [
  {
    id: "naver",
    company: "네이버",
    position: "백엔드 개발자",
    applyDate: "2024-02-15",
    status: "scheduled",
    statusText: "예정",
    stage: "지원 준비",
  },
  {
    id: "kakao",
    company: "카카오",
    position: "백엔드 개발자",
    applyDate: "2024-02-10",
    status: "document_submitted",
    statusText: "진행중",
    stage: "서류 제출 완료",
  },
  {
    id: "toss",
    company: "토스",
    position: "풀스택 개발자",
    applyDate: "2024-01-30",
    status: "interview",
    statusText: "진행중",
    stage: "면접 진행중",
  },
  {
    id: "line",
    company: "라인",
    position: "React 개발자",
    applyDate: "2024-02-20",
    status: "document_submitted",
    statusText: "진행중",
    stage: "서류 검토중",
  },
  {
    id: "coupang",
    company: "쿠팡",
    position: "풀스택 개발자",
    applyDate: "2024-01-25",
    status: "failed",
    statusText: "불합격",
    stage: "서류 불합격",
  },
  {
    id: "baemin",
    company: "배달의민족",
    position: "백엔드 개발자",
    applyDate: "2024-01-20",
    status: "passed",
    statusText: "합격",
    stage: "최종 합격",
  },
  {
    id: "nhn",
    company: "NHN",
    position: "프론트엔드 개발자",
    applyDate: "2024-01-15",
    status: "scheduled",
    statusText: "예정",
    stage: "지원 예정",
  },
];
