import TestImg from "../assets/testImg.png";
import type { ProjectCardProps } from "../components/atoms/card";

export const mockProjectData2: ProjectCardProps[] = [
  {
    id: 1,
    title: "모바일 쇼핑몰 앱2",
    content:
      "React와 SpringBoot를 활용한 크로스플랫폼 쇼핑몰 애플리케이션입니다. 사용자 친화적인 UI/UX와 안정적인 백엔드를 구현했습니다.",
    img: TestImg,
    type: "project",
    category: "모바일 앱",
    stack: ["React", "SpringBoot"],
    github: "https://github.com/",
    release: true,
    createTime: "2025-08-05",
    likeCount: 127,
    viewCount: 1234,
    writer: "지성현",
    commentCount: 3,
    writerImg: TestImg,
    comments: [
      {
        id: 1,
        writer: "김철수",
        writerImg: TestImg,
        commentText: "정말 좋은 프로젝트네요! UI가 깔끔하고 사용하기 편해요.",
        createTime: "2025-08-06T10:30:00",
      },
      {
        id: 2,
        writer: "이영희",
        writerImg: TestImg,
        commentText: "SpringBoot와 React 조합이 인상적입니다. 성능도 좋네요!",
        createTime: "2025-08-06T14:20:00",
      },
      {
        id: 3,
        writer: "박민준",
        writerImg: TestImg,
        commentText: "모바일 최적화가 잘 되어있어서 사용감이 좋습니다.",
        createTime: "2025-08-06T16:45:00",
      },
    ],
  },
  {
    id: 2,
    title: "웹 블로그 플랫폼",
    content:
      "Java 기반의 개인 블로그 관리 시스템입니다. 마크다운 지원과 댓글 시스템을 포함하고 있습니다.",
    img: TestImg,
    type: "project",
    stack: ["Java", "MySQL"],
    category: "웹 개발",
    github: "https://github.com/",
    release: true,
    createTime: "2025-08-04",
    likeCount: 89,
    viewCount: 856,
    writer: "지성현",
    commentCount: 2,
    writerImg: TestImg,
    comments: [
      {
        id: 4,
        writer: "최지원",
        writerImg: TestImg,
        commentText: "Java로 이런 깔끔한 블로그를 만들 수 있다니 대단해요!",
        createTime: "2025-08-06T09:15:00",
      },
      {
        id: 5,
        writer: "한동준",
        writerImg: TestImg,
        commentText: "마크다운 렌더링이 정말 깔끔하게 잘 되네요.",
        createTime: "2025-08-06T11:30:00",
      },
    ],
  },
  {
    id: 3,
    title: "React 관리자 대시보드",
    content:
      "데이터 시각화를 위한 관리자 대시보드입니다. Chart.js를 활용한 다양한 그래프와 실시간 데이터 모니터링 기능을 제공합니다.",
    img: TestImg,
    type: "project",
    stack: ["React", "Chart.js"],
    category: "웹 개발",
    github: "https://github.com/",
    release: true,
    createTime: "2025-08-03",
    likeCount: 156,
    viewCount: 1567,
    writer: "지성현",
    commentCount: 4,
    writerImg: TestImg,
    comments: [
      {
        id: 6,
        writer: "정수빈",
        writerImg: TestImg,
        commentText: "대시보드 디자인이 정말 깔끔하고 직관적이에요!",
        createTime: "2025-08-05T13:20:00",
      },
      {
        id: 7,
        writer: "오민석",
        writerImg: TestImg,
        commentText: "실시간 데이터 업데이트가 인상적입니다.",
        createTime: "2025-08-05T15:45:00",
      },
      {
        id: 8,
        writer: "류하은",
        writerImg: TestImg,
        commentText: "차트 애니메이션이 부드럽고 보기 좋네요.",
        createTime: "2025-08-06T08:10:00",
      },
      {
        id: 9,
        writer: "임채원",
        writerImg: TestImg,
        commentText: "반응형 디자인도 완벽하게 구현되어 있어요!",
        createTime: "2025-08-06T12:30:00",
      },
    ],
  },
  {
    id: 4,
    title: "네트워크 보안 모니터링",
    content:
      "Java 기반의 네트워크 보안 감시 도구입니다. 실시간 트래픽 분석과 이상 탐지 기능을 제공합니다.",
    img: TestImg,
    type: "project",
    stack: ["Java", "Spring Security"],
    category: "보안",
    github: "https://github.com/",
    release: true,
    createTime: "2025-08-02",
    likeCount: 203,
    viewCount: 1890,
    writer: "지성현",
    commentCount: 2,
    writerImg: TestImg,
    comments: [
      {
        id: 10,
        writer: "서준호",
        writerImg: TestImg,
        commentText:
          "보안 분야에서 이런 도구가 정말 필요했는데, 잘 만드셨네요!",
        createTime: "2025-08-05T16:20:00",
      },
      {
        id: 11,
        writer: "노예진",
        writerImg: TestImg,
        commentText: "실시간 모니터링 기능이 매우 유용할 것 같습니다.",
        createTime: "2025-08-06T10:15:00",
      },
    ],
  },
  {
    id: 5,
    title: "Spring 마이크로서비스",
    content:
      "Spring Boot를 활용한 마이크로서비스 아키텍처 구현 프로젝트입니다. Docker와 Kubernetes를 통한 컨테이너 오케스트레이션을 포함합니다.",
    img: TestImg,
    type: "project",
    stack: ["Spring", "Docker", "Kubernetes"],
    category: "웹 개발",
    github: "https://github.com/",
    release: true,
    createTime: "2025-08-01",
    likeCount: 178,
    viewCount: 1456,
    writer: "지성현",
    commentCount: 3,
    writerImg: TestImg,
    comments: [
      {
        id: 12,
        writer: "강민우",
        writerImg: TestImg,
        commentText: "마이크로서비스 아키텍처 구현이 정말 깔끔하네요!",
        createTime: "2025-08-05T14:30:00",
      },
      {
        id: 13,
        writer: "윤서아",
        writerImg: TestImg,
        commentText: "Docker 컨테이너화도 잘 되어있고, 확장성이 좋아 보입니다.",
        createTime: "2025-08-06T09:45:00",
      },
      {
        id: 14,
        writer: "조현우",
        writerImg: TestImg,
        commentText: "Kubernetes 설정 파일들도 참고하고 싶어요!",
        createTime: "2025-08-06T13:20:00",
      },
    ],
  },
  {
    id: 6,
    title: "전자상거래 플랫폼",
    content:
      "Spring 기반의 풀스택 전자상거래 웹 애플리케이션입니다. 결제 시스템, 재고 관리, 주문 처리 등 완전한 쇼핑몰 기능을 제공합니다.",
    img: TestImg,
    type: "project",
    stack: ["Spring", "JPA", "PostgreSQL"],
    writer: "지성현",
    category: "웹 개발",
    github: "https://github.com/",
    likeCount: 234,
    viewCount: 2103,
    release: true,
    createTime: "2025-07-30",
    commentCount: 5,
    writerImg: TestImg,
    comments: [
      {
        id: 15,
        writer: "이도현",
        writerImg: TestImg,
        commentText: "결제 시스템 구현이 정말 인상적입니다!",
        createTime: "2025-08-04T11:20:00",
      },
      {
        id: 16,
        writer: "김나연",
        writerImg: TestImg,
        commentText: "UI/UX가 사용자 친화적으로 잘 설계되어 있네요.",
        createTime: "2025-08-05T08:30:00",
      },
      {
        id: 17,
        writer: "박준영",
        writerImg: TestImg,
        commentText: "재고 관리 시스템이 실시간으로 잘 작동하네요!",
        createTime: "2025-08-05T15:45:00",
      },
      {
        id: 18,
        writer: "최유진",
        writerImg: TestImg,
        commentText: "관리자 페이지 기능들이 정말 완성도가 높아요.",
        createTime: "2025-08-06T07:15:00",
      },
      {
        id: 19,
        writer: "홍진우",
        writerImg: TestImg,
        commentText: "PostgreSQL과의 연동도 매끄럽게 잘 되어있습니다.",
        createTime: "2025-08-06T14:50:00",
      },
    ],
  },
  {
    id: 7,
    title: "Flutter 소셜미디어 앱",
    content:
      "Flutter를 사용한 크로스플랫폼 소셜미디어 애플리케이션입니다. 실시간 채팅, 사진 공유, 팔로우 시스템 등을 구현했습니다.",
    img: TestImg,
    writer: "지성현",
    type: "project",
    stack: ["Flutter", "Firebase", "Dart"],
    likeCount: 189,
    viewCount: 1678,
    category: "모바일 앱",
    github: "https://github.com/",
    release: true,
    createTime: "2025-07-28",
    commentCount: 4,
    writerImg: TestImg,
    comments: [
      {
        id: 20,
        writer: "안수현",
        writerImg: TestImg,
        commentText: "Flutter 앱이 네이티브처럼 부드럽게 동작하네요!",
        createTime: "2025-08-04T16:20:00",
      },
      {
        id: 21,
        writer: "장민재",
        writerImg: TestImg,
        commentText: "Firebase 연동이 잘 되어있어서 실시간 기능이 완벽해요.",
        createTime: "2025-08-05T12:45:00",
      },
      {
        id: 22,
        writer: "송지은",
        writerImg: TestImg,
        commentText: "UI 디자인이 정말 모던하고 깔끔합니다.",
        createTime: "2025-08-05T18:30:00",
      },
      {
        id: 23,
        writer: "김태민",
        writerImg: TestImg,
        commentText: "채팅 기능의 성능이 정말 좋네요!",
        createTime: "2025-08-06T11:10:00",
      },
    ],
  },
  {
    id: 8,
    title: "React 모바일 뱅킹 UI",
    content:
      "모바일 최적화된 React 뱅킹 애플리케이션 UI입니다. 보안을 고려한 사용자 인터페이스와 직관적인 거래 흐름을 구현했습니다.",
    img: TestImg,
    type: "project",
    stack: ["React", "TypeScript", "Styled-Components"],
    writer: "지성현",
    category: "모바일 앱",
    github: "https://github.com/",
    likeCount: 167,
    viewCount: 1432,
    release: true,
    createTime: "2025-07-25",
    commentCount: 3,
    writerImg: TestImg,
    comments: [
      {
        id: 24,
        writer: "배소영",
        writerImg: TestImg,
        commentText:
          "뱅킹 앱 UI로는 최고 수준이네요! 보안도 잘 고려된 것 같아요.",
        createTime: "2025-08-04T09:30:00",
      },
      {
        id: 25,
        writer: "신동혁",
        writerImg: TestImg,
        commentText:
          "TypeScript 사용으로 타입 안정성도 확보되어 있고 좋습니다.",
        createTime: "2025-08-05T14:15:00",
      },
      {
        id: 26,
        writer: "한예슬",
        writerImg: TestImg,
        commentText: "거래 플로우가 직관적이어서 사용하기 편해요!",
        createTime: "2025-08-06T10:45:00",
      },
    ],
  },
  {
    id: 9,
    title: "Python 데이터 분석 도구",
    content:
      "Python을 활용한 데이터베이스 최적화 및 분석 도구입니다. Pandas, NumPy를 사용한 데이터 처리와 시각화를 제공합니다.",
    writer: "지성현",
    img: TestImg,
    type: "project",
    stack: ["Python", "Pandas", "NumPy"],
    likeCount: 145,
    viewCount: 1289,
    category: "데이터 베이스",
    github: "https://github.com/",
    release: true,
    createTime: "2025-07-22",
    commentCount: 2,
    writerImg: TestImg,
    comments: [
      {
        id: 27,
        writer: "문지훈",
        writerImg: TestImg,
        commentText: "데이터 분석 결과가 매우 정확하고 유용합니다!",
        createTime: "2025-08-04T13:20:00",
      },
      {
        id: 28,
        writer: "전소미",
        writerImg: TestImg,
        commentText: "시각화 부분이 특히 인상적이에요. 그래프가 보기 좋네요!",
        createTime: "2025-08-05T17:40:00",
      },
    ],
  },
  {
    id: 10,
    title: "Docker 컨테이너 오케스트레이션",
    content:
      "Docker와 Kubernetes를 활용한 마이크로서비스 컨테이너 관리 시스템입니다. CI/CD 파이프라인과 모니터링 시스템을 포함합니다.",
    img: TestImg,
    type: "project",
    stack: ["Docker", "Kubernetes", "Jenkins"],
    category: "DevOps",
    writer: "지성현",
    github: "https://github.com/",
    likeCount: 198,
    viewCount: 1756,
    release: true,
    createTime: "2025-07-20",
    commentCount: 3,
    writerImg: TestImg,
    comments: [
      {
        id: 29,
        writer: "고준서",
        writerImg: TestImg,
        commentText: "DevOps 파이프라인 구성이 정말 체계적이네요!",
        createTime: "2025-08-04T15:30:00",
      },
      {
        id: 30,
        writer: "이채린",
        writerImg: TestImg,
        commentText: "Kubernetes 설정이 완벽하게 구성되어 있어요.",
        createTime: "2025-08-05T11:20:00",
      },
      {
        id: 31,
        writer: "정우진",
        writerImg: TestImg,
        commentText: "CI/CD 자동화가 정말 잘 되어있습니다!",
        createTime: "2025-08-06T09:15:00",
      },
    ],
  },
  {
    id: 11,
    title: "Python 웹 서버 프레임워크",
    content:
      "FastAPI를 사용한 고성능 웹 서버 구축 프로젝트입니다. 비동기 처리와 자동 API 문서화 기능을 포함하고 있습니다.",
    likeCount: 134,
    viewCount: 1123,
    img: TestImg,
    type: "project",
    stack: ["Python", "FastAPI", "SQLAlchemy"],
    category: "서버",
    github: "https://github.com/",
    writer: "지성현",
    release: true,
    createTime: "2025-07-18",
    commentCount: 4,
    writerImg: TestImg,
    comments: [
      {
        id: 32,
        writer: "홍수빈",
        writerImg: TestImg,
        commentText:
          "FastAPI의 성능이 정말 뛰어나네요! API 문서도 자동으로 생성되고.",
        createTime: "2025-08-03T14:50:00",
      },
      {
        id: 33,
        writer: "양진호",
        writerImg: TestImg,
        commentText: "비동기 처리 구현이 매우 깔끔합니다.",
        createTime: "2025-08-04T10:30:00",
      },
      {
        id: 34,
        writer: "구민정",
        writerImg: TestImg,
        commentText: "SQLAlchemy ORM 사용법도 참고가 많이 됩니다!",
        createTime: "2025-08-05T16:20:00",
      },
      {
        id: 35,
        writer: "차준혁",
        writerImg: TestImg,
        commentText: "API 응답 속도가 정말 빠르네요!",
        createTime: "2025-08-06T12:40:00",
      },
    ],
  },
  {
    id: 12,
    title: "Kubernetes 클러스터 관리",
    content:
      "Docker와 Kubernetes를 활용한 대규모 클러스터 관리 시스템입니다. 자동 스케일링, 로드 밸런싱, 헬스 체크 기능을 포함합니다.",
    img: TestImg,
    type: "project",
    stack: ["Docker", "Kubernetes", "Helm"],
    likeCount: 176,
    viewCount: 1534,
    writer: "지성현",
    category: "DevOps",
    github: "https://github.com/",
    release: true,
    createTime: "2025-07-15",
    commentCount: 2,
    writerImg: TestImg,
    comments: [
      {
        id: 36,
        writer: "임상혁",
        writerImg: TestImg,
        commentText:
          "Kubernetes 클러스터 관리가 이렇게 체계적으로 구성될 수 있다니 놀랍네요!",
        createTime: "2025-08-03T16:30:00",
      },
      {
        id: 37,
        writer: "소유진",
        writerImg: TestImg,
        commentText: "Helm 차트 구성도 매우 깔끔하고 재사용성이 좋아 보입니다.",
        createTime: "2025-08-05T13:45:00",
      },
    ],
  },
  {
    id: 13,
    title: "React 기업 포털 시스템",
    content:
      "대기업용 통합 포털 솔루션 개발 프로젝트입니다. 사용자 권한 관리, 문서 관리, 업무 협업 도구 등을 포함한 종합적인 업무 환경을 제공합니다.",
    img: TestImg,
    type: "project",
    stack: ["React", "Redux", "Node.js"],
    category: "웹 개발",
    github: "https://github.com/",
    likeCount: 156,
    viewCount: 1398,
    release: true,
    createTime: "2025-07-12",
    writer: "지성현",
    commentCount: 3,
    writerImg: TestImg,
    comments: [
      {
        id: 38,
        writer: "남궁민수",
        writerImg: TestImg,
        commentText: "기업용 포털로서 필요한 모든 기능이 잘 구현되어 있네요!",
        createTime: "2025-08-03T11:20:00",
      },
      {
        id: 39,
        writer: "서지영",
        writerImg: TestImg,
        commentText: "권한 관리 시스템이 매우 세밀하고 보안성이 좋아 보입니다.",
        createTime: "2025-08-04T14:15:00",
      },
      {
        id: 40,
        writer: "황도현",
        writerImg: TestImg,
        commentText: "Redux 상태 관리가 복잡한 기업 환경에 최적화되어 있어요!",
        createTime: "2025-08-05T10:30:00",
      },
    ],
  },
];
